version: '3.8'
services:
  mysql:
    platform: linux/amd64
    image: mysql:8
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      start_interval: 10s
      start_period: 40s
      timeout: 20s
      retries: 10
    expose:
      - "3306"
    ports:
      - "4000:3306"
    volumes:
      - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: testdb
  
  gosocial:
    build: 
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/go/src/gosocial
    ports:
      - "8080:8080"
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: 1234
      DB_PORT: 3306
      DB_NAME: testdb
    links:
      - mysql
    depends_on:
      mysql:
        condition: service_healthy
volumes:
  db_data: